#!/bin/sh
#
# Script name: bb_IDP_func_TSNR
#
# Description: Script to generate the IDPs related to TSNR for fMRI.
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

origDir=`pwd`
scriptName=`basename "$0"`
direc=$1

cd $direc

basefMRI="fMRI/"
#if [ -d $basefMRI/unusable ] ; then
#    basefMRI="$basefMRI/unusable"
#fi

baserfMRI="$basefMRI/rfMRI.ica/"
basetfMRI="$basefMRI/tfMRI.feat/"

result=""

for i in $baserfMRI/filtered_func_data $baserfMRI/filtered_func_data_clean $basetfMRI/filtered_func_data ; do
  if [ -f ${i}.nii.gz ] ; then
    nameFil=`basename basetfMRI`
    fslmaths $i -Tstd /tmp/${nameFil}_SNR_$1
    fslmaths $i -Tmean -div /tmp/${nameFil}_SNR_$1 /tmp/${nameFil}_SNR_$1
    TheSNR=`fslstats /tmp/${nameFil}_SNR_$1 -l 0.1 -p 50`
    TheSNRrecip=`echo "10 k 1 $TheSNR / p" | dc -`
    result="$result $TheSNRrecip"
    fmriNumVol=`${FSLDIR}/bin/fslval $1/fMRI/rfMRI_$2.nii.gz dim4
    result="$result $fmriNumVol" 
    imrm /tmp/${nameFil}_SNR_$1
  else
    result="$result NaN"
  fi
done


mkdir -p IDP_files

echo $result > IDP_files/$scriptName.txt
echo $result

cd $origDir


