#!/bin/sh
#
# Script name: bb_IDP_func_ICA_netmats
#
# Description: Script to generate the IDPs related to netmats from resting fMRI
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
origDir=`pwd`
scriptName=`basename "$0"`
direc=$1

cd $direc

basefMRI="fMRI/"
#if [ -d $basefMRI/unusable ] ; then
#    basefMRI="$basefMRI/unusable"
#fi

mkdir -p IDP_files

cd $basefMRI

matlab -nojvm -nodisplay -nosplash -r "addpath('$BB_BIN_DIR/bb_IDP_pipeline/scripts/'); $scriptName ; exit"
#matlab -nojvm -nodisplay -nosplash -r "addpath('$BB_BIN_DIR/bb_IDP_pipeline/scripts/'); path"

cd $origDir


