#!/bin/sh
#
# Script name: bb_IDP_T1_SIENAX
#
# Description: Script to generate the IDPs related to the alginment between
#			   T1 and MNI template.
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
ST=$FSLDIR/data/standard
MC=$FSLDIR/etc/flirtsch/measurecost1.sch

origDir=`pwd`
scriptName=`basename "$0"`
direc=$1

cd $direc

baseT1="T1"
#if [ -d T1/unusable ] ; then
#    baseT1="T1/unusable"
#fi

result1="NaN"
result2="NaN"
result3="NaN"

if [ -f $baseT1/T1_brain.nii.gz ] && [ -f $baseT1/transforms/T1_to_MNI_linear.mat ] ; then
  result1=`${FSLDIR}/bin/flirt -in $baseT1/T1_brain -ref $ST/MNI152_T1_1mm_brain -refweight $ST/MNI152_T1_1mm_brain_mask -init $baseT1/transforms/T1_to_MNI_linear.mat -schedule $MC | head -1 | cut -f1 -d' '`
fi

if [ -f $baseT1/T1_brain_to_MNI.nii.gz ] ; then
  result2=`${FSLDIR}/bin/flirt -in $baseT1/T1_brain_to_MNI -ref $ST/MNI152_T1_1mm_brain -refweight $ST/MNI152_T1_1mm_brain_mask -schedule $MC | head -1 | cut -f1 -d' ' `
fi


if [ -f $baseT1/transforms/T1_to_MNI_warp_jac.nii.gz ] ; then
  ${FSLDIR}/bin/fslmaths $baseT1/transforms/T1_to_MNI_warp_jac -sub 1 -sqr /tmp/tmpjac_$1
  result3=`${FSLDIR}/bin/fslstats /tmp/tmpjac_$1 -k $ST/MNI152_T1_1mm_brain_mask -m `
  ${FSLDIR}/bin/imrm /tmp/tmpjac_$1
fi

result="$result1 $result2 $result3"

mkdir -p IDP_files

echo $result > IDP_files/$scriptName.txt
echo $result
    
cd $origDir


