#!/bin/sh
#
# Script name: bb_IDP_T1_SIENAX
#
# Description: Script to generate the IDPs related to SIENAX
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

origDir=`pwd`
scriptName=`basename "$0"`
direc=$1

cd $direc

baseT1="T1"
#if [ -d T1/unusable ] ; then
#    baseT1="T1/unusable"
#fi

#Setting the string of NaN in case there is a problem.
numVars="11"
result="";
for i in $(seq 1 $numVars) ; do 
    result="NaN $result" ; 
done 


if [ ! -f $baseT1/T1_sienax/T1_sienax.txt ] && [ -f $baseT1/T1_sienax/report.sienax ] ; then
  echo `cat $baseT1/T1_sienax/report.sienax` | cut -d " " -f2,7,8,12,13,17,18,20,21,23,24 > $baseT1/T1_sienax/T1_sienax.txt
  result=`cat $baseT1/T1_sienax/T1_sienax.txt` 

elif [ -f $baseT1/T1_sienax/T1_sienax.txt ] ; then
    result=`cat $baseT1/T1_sienax/T1_sienax.txt` 
fi

mkdir -p IDP_files

echo $result > IDP_files/$scriptName.txt
echo $result

cd $origDir


