#!/bin/sh
#
# Script name: bb_IDP_T2_FLAIR_WMH
#
# Description: Script to generate the IDPs related to White Matter Hyperintens.
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

origDir=`pwd`
scriptName=`basename "$0"`
direc=$1

dirT2=$direc/T2_FLAIR

#Setting the string of NaN in case there is a problem.
result="NaN"

if [ -f $dirT2/lesions/volume.txt ] ; then
    result=`cat $dirT2/lesions/volume.txt`
fi

mkdir -p $direc/IDP_files

echo $result > $direc/IDP_files/$scriptName.txt
echo $result
    
cd $origDir


