#!/bin/sh
#
# Script name: bb_IDP_T1_FIRST_vols
#
# Description: Script to generate the IDPs related to subcortical volumes
#			   calculated with FIRST.
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

origDir=`pwd`
scriptName=`basename "$0"`
direc=$1

cd $direc

baseT1="T1"

#Setting the string of NaN in case there is a problem.
numVars="15"
result="";
for i in $(seq 1 $numVars) ; do 
    result="NaN $result" ; 
done 


if [ -f $baseT1/T1_first/T1_first_all_fast_firstseg.nii.gz ] ; then
    result=`${FSLDIR}/bin/fslstats $baseT1/T1_first/T1_first_all_fast_firstseg -H 58 0.5 58.5 | sed 's/\.000000//g' | awk 'BEGIN { ORS = " " } { print }'| awk '{print $10 " " $49 " " $11 " " $50 " " $12 " " $51 " " $13 " " $52 " " $17 " " $53 " " $18 " " $54 " " $26 " " $58 " " $16 }' `
fi

mkdir -p IDP_files

echo $result > IDP_files/$scriptName.txt
echo $result
    
cd $origDir


