#!/usr/bin/env bash
#
# Script name: bb_autoPtx
#
# Description: Biobank version of the autoPtx script.
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

logDir=$PWD/$1"/logs/"
logFile=$logDir"bb_autoPtx__"$1"__"$$".log"

exec 3>&1 4>&2 1> $logFile 2>&1

. $BB_BIN_DIR/bb_pipeline_tools/bb_set_header 

execPath=`dirname $0`

if [ "$2" == "" ]; then
    holdJob=""
else
	holdJob=" -j $2 "
fi

if [ "$3" == "" ]; then
    MNI_to_FA_warp=../TBSS/FA/MNI_to_dti_FA_warp.nii.gz
else
	MNI_to_FA_warp=$3
fi

if [ "$4" == "" ]; then
    FA_to_MNI_warp=../TBSS/FA/dti_FA_to_MNI_warp.nii.gz
else
	FA_to_MNI_warp=$4
fi

direc=$PWD/$1/dMRI	

cd $direc

mkdir -p $direc/autoptx_preproc

cd autoptx_preproc

structures=$execPath/structureList

listJobs=""

while read line ; do
    echo $line
    struct=`echo $line | awk '{print $1}'`
    nseed=`echo $line | awk '{print $2}'`
    #wallt=`echo $line | awk '{print $3}' | tr ':' ' '`
    #hours=`echo $wallt | awk '{print $1}'`
    #minutes=`echo $wallt | awk '{print $2}'`
    #time=$(( 60 * hours + minutes ))
    #listJobs=`${FSLDIR}/bin/fsl_sub -N "bb_autoPtx_$1" -T $time   -l $logDir/autoPtx $holdJob  $execPath/bb_trackSubjectStruct $1/dMRI $struct $nseed $MNI_to_FA_warp $FA_to_MNI_warp `",$listJobs"
    time=`echo $line | awk '{print $3}'`
    #listJobs=`${FSLDIR}/bin/fsl_sub  -T $time -N "bb_autoPtx_${struct}_${1}" -l $logDir/autoPtx $holdJob  $execPath/bb_trackSubjectStruct $1/dMRI $struct $nseed $MNI_to_FA_warp $FA_to_MNI_warp `",$listJobs"
    listJobs=`${FSLDIR}/bin/fsl_sub  -q ${QUEUE_STANDARD} -N "bb_autoPtx_${struct}_${1}" -l $logDir/autoPtx $holdJob  $execPath/bb_trackSubjectStruct $1/dMRI $struct $nseed $MNI_to_FA_warp $FA_to_MNI_warp `",$listJobs"

done < $structures

. $BB_BIN_DIR/bb_pipeline_tools/bb_set_footer 

exec 1>&3 2>&4

echo ${listJobs%","}
