#!/usr/bin/env bash
#
# Script name: bb_eddy_wrap
#
# Description: Script to run eddy_cuda with the appropriate parameters.
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

. $BB_BIN_DIR/bb_pipeline_tools/bb_set_header 

baseDir=$1
#bestInd=`cat $baseDir/fieldmap/total_B0_AP_best_index.txt`

#$FSLDIR/bin/eddy_cuda --imain=$baseDir/dMRI/dMRI/AP.nii.gz --mask=$baseDir/dMRI/dMRI/nodif_brain_mask.nii.gz --topup=$baseDir/fieldmap/fieldmap_out --acqp=$baseDir/fieldmap/acqparams.txt --index=$baseDir/dMRI/dMRI/eddy_index.txt --bvecs=$baseDir/dMRI/dMRI/bvecs --bvals=$baseDir/dMRI/dMRI/bvals --out=$baseDir/dMRI/dMRI/data --ref_scan_no=$bestInd --flm=quadratic --resamp=jac --slm=linear --fwhm=2 --ff=5  --sep_offs_move --nvoxhp=1000 --very_verbose  --repol --rms --estimate_move_by_susceptibility --data_is_shelled

if [ "$SynB0" == "y" ]; then
    eddy_openmp --imain=$baseDir/dMRI/dMRI/DWI.nii.gz --mask=$baseDir/dMRI/dMRI/rawDTI_B0_brain_mask.nii.gz --topup=$baseDir/dMRI/dMRI/SynB0/topup --acqp=$baseDir/dMRI/dMRI/acqparams.txt --index=$baseDir/dMRI/dMRI/eddy_index.txt --bvecs=$baseDir/dMRI/dMRI/bvecs --bvals=$baseDir/dMRI/dMRI/bvals --out=$baseDir/dMRI/dMRI/data --flm=quadratic --resamp=jac --slm=linear --fwhm=2 --ff=5  --sep_offs_move --nvoxhp=1000 --repol --rms --cnr_maps -v
else
    eddy_openmp --imain=$baseDir/dMRI/dMRI/DWI.nii.gz --mask=$baseDir/dMRI/dMRI/rawDTI_B0_brain_mask.nii.gz --acqp=$baseDir/dMRI/dMRI/acqparams.txt --index=$baseDir/dMRI/dMRI/eddy_index.txt --bvecs=$baseDir/dMRI/dMRI/bvecs --bvals=$baseDir/dMRI/dMRI/bvals --out=$baseDir/dMRI/dMRI/data --flm=quadratic --resamp=jac --slm=linear --fwhm=2 --ff=5  --sep_offs_move --nvoxhp=1000 --repol --rms --cnr_maps -v
fi

. $BB_BIN_DIR/bb_pipeline_tools/bb_set_footer 
