#!/usr/bin/env bash
#
# Script name: bb_post_eddy
#
# Description: Script to run GDC and select 1 cell on the dMRI data after eddy.
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##. $BB_BIN_DIR/bb_pipeline_tools/bb_set_header 

baseDir=$1
# no gdc for our data
###$BB_BIN_DIR/bb_pipeline_tools/bb_GDC --workingdir=$baseDir/dMRI/dMRI/data_GDC --in=$baseDir/dMRI/dMRI/data.nii.gz --out=$baseDir/dMRI/dMRI/data_ud.nii.gz --owarp=$baseDir/dMRI/dMRI/data_ud_warp.nii.gz
$FSLDIR/bin/fslroi $baseDir/dMRI/dMRI/data.nii.gz $baseDir/dMRI/dMRI/data_B0.nii.gz 0 1

### final dti brain mask by zwang
$FSLDIR/bin/bet $baseDir/dMRI/dMRI/data_B0.nii.gz $baseDir/dMRI/dMRI/nodif_brain -f 0.20 -g 0 -m -n
#Correct input for dtifit
$BB_BIN_DIR/bb_diffusion_pipeline/bb_select_dwi_vols $baseDir/dMRI/dMRI/data.nii.gz $baseDir/dMRI/dMRI/bvals $baseDir/dMRI/dMRI/data_1_shell 1000 1 $baseDir/dMRI/dMRI/bvecs

##. $BB_BIN_DIR/bb_pipeline_tools/bb_set_footer 
