#!/usr/bin/env bash
#
# Script name: bb_pre_eddy
#
# Description: Script to prepare the dMRI data for eddy
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

. $BB_BIN_DIR/bb_pipeline_tools/bb_set_header 

direc=$PWD/$1
mkdir -p $direc/dMRI/dMRI

# Prepare data for eddy, dtifit and bedpostx.
#ln -s ../raw/AP.nii.gz $direc/dMRI/dMRI/AP.nii.gz  ###### our data no AP and PA
#ln -s ../../fieldmap/fieldmap_iout_mean.nii.gz $direc/dMRI/dMRI/nodif.nii.gz  #### we don't have fieldmap either
#ln -s ../../fieldmap/fieldmap_mask.nii.gz $direc/dMRI/dMRI/nodif_brain_mask.nii.gz
#ln -s ../../fieldmap/fieldmap_mask_ud.nii.gz $direc/dMRI/dMRI/nodif_brain_mask_ud.nii.gz

#fslmaths $direc/dMRI/dMRI/nodif.nii.gz -mul $direc/dMRI/dMRI/nodif_brain_mask.nii.gz $direc/dMRI/dMRI/nodif_brain.nii.gz
#cp $direc/dMRI/raw/AP.bval $direc/dMRI/dMRI/bvals  #### our data don't have AP and PA direction
#cp $direc/dMRI/raw/AP.bvec $direc/dMRI/dMRI/bvecs  #### our data don't have AP and PA direction

ln -s $direc/dMRI/raw/dwi.nii.gz $direc/dMRI/dMRI/DWI.nii.gz
cp $direc/dMRI/raw/dwi.bval $direc/dMRI/dMRI/bvals
cp $direc/dMRI/raw/dwi.bvec $direc/dMRI/dMRI/bvecs

#TODO: detect B0 automatically
# extract B0 (assumes B0 is first volume)
${FSLDIR}/bin/fslroi $direc/dMRI/dMRI/DWI $direc/dMRI/dMRI/DWI_B0 0 1

# register T1 to DTI for preliminary DTI mask for eddy
mkdir -p ${direc}/dMRI/dMRI/transforms
${BB_BIN_DIR}/bb_structural_pipeline/bb_epi_reg --epi=$direc/dMRI/dMRI/DWI_B0 --t1=$direc/T1/T1 --t1brain=$direc/T1/T1_brain --out=$direc/dMRI/dMRI/transforms/rawDTI_to_T1 --wmseg=$direc/T1/T1_fast/T1_brain_WM_mask

# create inverse warp
${FSLDIR}/bin/convert_xfm -omat $direc/dMRI/dMRI/transforms/T1_to_rawDTI.mat -inverse $direc/dMRI/dMRI/transforms/rawDTI_to_T1.mat

# apply warp to get brain mask for uncorrected DTI data
${FSLDIR}/bin/applywarp -i $direc/T1/T1_brain_mask -r $direc/dMRI/dMRI/DWI_B0 -o $direc/dMRI/dMRI/rawDTI_B0_brain_mask --premat=$direc/dMRI/dMRI/transforms/T1_to_rawDTI.mat --interp=nn


indx=""

n=`${FSLDIR}/bin/fslval $direc/dMRI/dMRI/DWI.nii.gz dim4` #### our data don't have AP and PA direction

for (( i=1; i <= ${n}; i++)); do
    indx="$indx 1"
done

echo $indx > $direc/dMRI/dMRI/eddy_index.txt


# Creation of acqparam file, borrowed from TOPUP prep in bb_prepare_struct_field
EPIfactor=50 #aka Echo Train Length, number of lines
dtiDwell=`$BB_BIN_DIR/bb_pipeline_tools/bb_get_dwell_time $direc/dMRI/raw/dwi.nii.gz`
topupValue="0"`echo "scale=4;("$dtiDwell" * ("$EPIfactor" -1.0)) / 1000.0 "| bc` #aka Total Readout Time

cat /dev/null > $direc/dMRI/dMRI/acqparams.txt 

#camCAN encoding is A>>P
printf "0 -1 0 $topupValue\n" >>$direc/dMRI/dMRI/acqparams.txt


## set acqparams.txt by zwang
# exact params may not matter much if not doing TOPUP, or if two blips for TOPUP have the same Total Readout Time
#printf "0 1 0 0.095" > $direc/dMRI/dMRI/acqparams.txt

. $BB_BIN_DIR/bb_pipeline_tools/bb_set_footer