#!/bin/sh
#
# Script name: fsl_swi
#
# Description: Script to run the swMRI processing.
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


FSL_SWIDIR=$( cd $(dirname $0) ; pwd)
. ${FSL_SWIDIR}/settings.sh

${FSL_SWIDIR}/call_matlab.sh -l $1/logs/bb_swi_matlab_$2.log -f swiProcessing $1

