#!/usr/bin/env bash
#
# Script name: bb_post_topup
#
# Description: Script to organise files and generate averages after topup.
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson	
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


. $BB_BIN_DIR/bb_pipeline_tools/bb_set_header 

#Get corrected B=0 for AP and PA and average them avoiding zero values 
${FSLDIR}/bin/applytopup --imain=$1/fieldmap/B0_AP --datain=$1/fieldmap/acqparams.txt --inindex=1 --topup=$1/fieldmap/fieldmap_out --out=$1/fieldmap/B0_AP_corr_tmp --method=jac
${FSLDIR}/bin/applytopup --imain=$1/fieldmap/B0_PA --datain=$1/fieldmap/acqparams.txt --inindex=2 --topup=$1/fieldmap/fieldmap_out --out=$1/fieldmap/B0_PA_corr_tmp --method=jac

    #Get a mask with the zero-valued voxels for AP and PA
$BB_BIN_DIR/bb_structural_pipeline/bb_mask_negatives_4D.py -i $1/fieldmap/B0_AP_corr_tmp.nii.gz -o $1/fieldmap/B0_AP_zero_mask_tmp.nii.gz -z True
$BB_BIN_DIR/bb_structural_pipeline/bb_mask_negatives_4D.py -i $1/fieldmap/B0_PA_corr_tmp.nii.gz -o $1/fieldmap/B0_PA_zero_mask_tmp.nii.gz -z True

    #Multiply the previous mask by the other direction and thus, get the values in AP for which we have zero in PA (And viceversa)
${FSLDIR}/bin/fslmaths $1/fieldmap/B0_AP_corr_tmp.nii.gz -mul $1/fieldmap/B0_PA_zero_mask_tmp.nii.gz $1/fieldmap/AP_masked_tmp.nii.gz
${FSLDIR}/bin/fslmaths $1/fieldmap/B0_PA_corr_tmp.nii.gz -mul $1/fieldmap/B0_AP_zero_mask_tmp.nii.gz $1/fieldmap/PA_masked_tmp.nii.gz
    
    #Add the previous result to B=0 AP and PA
${FSLDIR}/bin/fslmaths $1/fieldmap/B0_AP_corr_tmp.nii.gz -add $1/fieldmap/PA_masked_tmp.nii.gz $1/fieldmap/B0_AP_fixed_tmp.nii.gz
${FSLDIR}/bin/fslmaths $1/fieldmap/B0_PA_corr_tmp.nii.gz -add $1/fieldmap/AP_masked_tmp.nii.gz $1/fieldmap/B0_PA_fixed_tmp.nii.gz

    #Merge and average them
${FSLDIR}/bin/fslmerge -t $1/fieldmap/fieldmap_iout.nii.gz $1/fieldmap/B0_AP_fixed_tmp.nii.gz $1/fieldmap/B0_PA_fixed_tmp.nii.gz
${FSLDIR}/bin/fslmaths $1/fieldmap/fieldmap_iout.nii.gz -Tmean $1/fieldmap/fieldmap_iout_mean.nii.gz


#GDC to iout_mean
$BB_BIN_DIR/bb_pipeline_tools/bb_GDC --workingdir=$1/fieldmap//fieldmap_iout_GDC/ --in=$1/fieldmap/fieldmap_iout_mean.nii.gz --out=$1/fieldmap/fieldmap_iout_mean_ud.nii.gz --owarp=$1/fieldmap/fieldmap_iout_mean_ud_warp.nii.gz
#TODO: This was the previous copy. The geometry is exactly the same for B0_AP and fieldmap_iout_mean -- fslcpgeom $1/fieldmap/fieldmap_iout_mean.nii.gz $1/fieldmap/fieldmap_fout.nii.gz
${FSLDIR}/bin/fslcpgeom $1/fieldmap/B0_AP.nii.gz $1/fieldmap/fieldmap_fout.nii.gz


#Clean temporary files
${FSLDIR}/bin/imrm *_tmp.nii.gz

# Get the topup iout (magnitude) to struct space and apply the transformation to fout (fieldmap)
$BB_BIN_DIR/bb_structural_pipeline/bb_epi_reg --epi=$1/fieldmap/fieldmap_iout_mean_ud.nii.gz --t1=$1/T1/T1.nii.gz --t1brain=$1/T1/T1_brain.nii.gz --out=$1/fieldmap/fieldmap_iout_to_T1 --wmseg=$1/T1/T1_fast/T1_brain_WM_mask.nii.gz
${FSLDIR}/bin/applywarp --rel -i $1/fieldmap/fieldmap_fout.nii.gz -r $1/T1/T1.nii.gz -o $1/fieldmap/fieldmap_fout_to_T1 -w $1/fieldmap/fieldmap_iout_mean_ud_warp.nii.gz  --postmat=$1/fieldmap/fieldmap_iout_to_T1.mat --interp=spline

# Mask the warped fout (fieldmap) using T1 brain mask
${FSLDIR}/bin/fslmaths $1/fieldmap/fieldmap_fout_to_T1 -mul $1/T1/T1_brain_mask.nii.gz $1/fieldmap/fieldmap_fout_to_T1_brain.nii.gz

# Multiply the warped & masked fout (fieldmap) by 2*Pi to have it in radians
${FSLDIR}/bin/fslmaths $1/fieldmap/fieldmap_fout_to_T1_brain.nii.gz -mul 6.283185 $1/fieldmap/fieldmap_fout_to_T1_brain_rad.nii.gz

# Generate a mask for topup output by inverting the previous registration and applying it to T1 brain mask
${FSLDIR}/bin/convert_xfm -omat $1/fieldmap/T1_to_fieldmap_iout.mat -inverse $1/fieldmap/fieldmap_iout_to_T1.mat
${FSLDIR}/bin/fslmaths $1/T1/T1_brain_mask.nii.gz -thr 0.1 -kernel sphere 1.1 -dilF -bin -fillh $1/T1/T1_brain_mask_dil.nii.gz
${FSLDIR}/bin/flirt -in $1/T1/T1_brain_mask_dil.nii.gz -ref $1/fieldmap/fieldmap_iout_mean.nii.gz -applyxfm -init $1/fieldmap/T1_to_fieldmap_iout.mat -out $1/fieldmap/fieldmap_mask_ud.nii.gz -interp trilinear
${FSLDIR}/bin/fslmaths $1/fieldmap/fieldmap_mask_ud.nii.gz -thr 0.25 -bin -fillh $1/fieldmap/fieldmap_mask_ud.nii.gz

#Warp the dilated T1 brain mask to the Gradient Distorted space by inverting the 
${FSLDIR}/bin/invwarp --ref=$1/fieldmap/fieldmap_iout_mean.nii.gz -w $1/fieldmap/fieldmap_iout_mean_ud_warp.nii.gz -o $1/fieldmap/fieldmap_iout_mean_ud_inv_warp.nii.gz
${FSLDIR}/bin/applywarp --rel -i $1/T1/T1_brain_mask_dil.nii.gz -r $1/fieldmap/fieldmap_iout_mean.nii.gz -o $1/fieldmap/fieldmap_mask.nii.gz --premat=$1/fieldmap/T1_to_fieldmap_iout.mat -w $1/fieldmap/fieldmap_iout_mean_ud_inv_warp.nii.gz   --interp=trilinear
${FSLDIR}/bin/fslmaths $1/fieldmap/fieldmap_mask.nii.gz -thr 0.25 -bin -fillh $1/fieldmap/fieldmap_mask.nii.gz

. $BB_BIN_DIR/bb_pipeline_tools/bb_set_footer 
