#!/bin/bash
#### bb_post_probtrackx2
#
# concatenate parallelized probtrackx outputs
# and clean up probtrackx log files
#


. $BB_BIN_DIR/bb_pipeline_tools/bb_set_header

set +e

subjdir=`fsl_abspath $1`
subjdir=`echo ${subjdir} | sed 's/\/$/$/g'`
echo subjectdir is $subjdir


python $BB_BIN_DIR/bb_diffusion_pipeline/tvb_probtrackx2/tvb_concat_probtrackx2.py $subjdir ${PARC_NAME} $PROBTRACKX_GPU

# move probtrackx logs to subject log directory
# mv bb_probtrackx_${1}.e* $subjdir/logs/.
# mv bb_probtrackx*_${1}.o* $subjdir/logs/.


#generate tvb input zip
mkdir $subjdir/tvb_inputs
mkdir $subjdir/tvb_inputs/structural_inputs
mkdir $subjdir/tvb_inputs/misc_inputs
mkdir $subjdir/tvb_inputs/functional_inputs



cp $subjdir/dMRI/sc_${PARC_NAME}.txt $subjdir/dMRI/distance_${PARC_NAME}.txt $subjdir/T2_FLAIR/lesions/volume.txt $subjdir/tvb_inputs

mv $subjdir/tvb_inputs/sc_${PARC_NAME}.txt $subjdir/tvb_inputs/structural_inputs/weights.txt
mv $subjdir/tvb_inputs/distance_${PARC_NAME}.txt $subjdir/tvb_inputs/structural_inputs/tract_lengths.txt
mv $subjdir/tvb_inputs/volume.txt $subjdir/tvb_inputs/misc_inputs/lesion_volume.txt



array=()
while IFS=  read -r -d $'\0'; do
    array+=("$REPLY")
done < <(find $subjdir/fMRI -maxdepth 1 -type d -name "*.ica" -print0)

#for each .ica file
for t in ${array[@]}; do
	mkdir $subjdir/tvb_inputs/functional_inputs/`basename $t`
	cp $t/fc_${PARC_NAME}.txt $t/ts_${PARC_NAME}.txt $subjdir/tvb_inputs/functional_inputs/`basename $t`
	mv $subjdir/tvb_inputs/functional_inputs/`basename $t`/fc_${PARC_NAME}.txt $subjdir/tvb_inputs/functional_inputs/`basename $t`/`basename $t`_functional_connectivity.txt
	mv $subjdir/tvb_inputs/functional_inputs/`basename $t`/ts_${PARC_NAME}.txt $subjdir/tvb_inputs/functional_inputs/`basename $t`/`basename $t`_time_series.txt

	
done


#generate cortical.txt and centres.txt
python $BB_BIN_DIR/bb_diffusion_pipeline/tvb_probtrackx2/tvb_generate_centres_cortical.py $subjdir $PARC_LUT ${PARC_NAME}


subj=$1
if [[ "$subj" =~ '/'$ ]]; then 
  subj=${subj%?}
fi
subj=`basename $subj`

cd $subjdir/tvb_inputs && zip -r ./structural_inputs.zip ./structural_inputs && cd -

rm -rf $subjdir/tvb_inputs/structural_inputs

mv ${subjdir}/tvb_inputs ${subjdir}/${subj}_${PARC_NAME}_tvb_inputs
cd $subjdir && zip -r ./${subj}_${PARC_NAME}_tvb_inputs.zip ./${subj}_${PARC_NAME}_tvb_inputs && cd -

rm -rf $subjdir/${subj}_${PARC_NAME}_tvb_inputs


set -e
. $BB_BIN_DIR/bb_pipeline_tools/bb_set_footer


# mkdir tvb_inputs
# mv ./dMRI/sc.txt ./tvb_inputs/structural_weights.txt
# mv ./dMRI/tl.txt ./tvb_inputs/tract_lengths.txt
