#!/bin/sh

#   bb_fix - wrapper script for FIX, for UK Biobank pipelines
#
#   Stephen Smith, FMRIB Analysis Group
#
#   Copyright (C) 2015 University of Oxford
#
#   SHCOPYRIGHT

FSL_FIXDIR=$( cd $(dirname $0) ; pwd)
export FSL_FIXDIR
# All fix settings are held in the settings.sh file - edit this file to suit your setup
. ${FSL_FIXDIR}/settings.sh

#############################################################

[ "$1" = "" ] && exit

cd $1/fMRI/rfMRI.ica

imcp ../../T1/T1_fast/T1_brain_pveseg reg/highres_pveseg

invwarp --ref=reg/example_func -w reg/example_func2standard_warp -o reg/standard2example_func_warp

echo "Running fix..."
${FSL_FIXDIR}/fix . ${FSL_FIXDIR}/training_files/${TRAINING_FILE} 20 -m -h 100
echo "Done."

mkdir -p reg_standard
applywarp --ref=reg/standard --in=filtered_func_data_clean --out=reg_standard/filtered_func_data_clean --warp=reg/example_func2standard_warp --interp=spline

fslmaths reg_standard/filtered_func_data_clean -mas $BBDIR/fbp/templates/MNI152_T1_2mm_brain_mask_bin reg_standard/filtered_func_data_clean
fslmaths reg_standard/filtered_func_data_clean -Tstd -bin reg_standard/filtered_func_data_clean_stdmask

