#!/bin/sh
#
# Script name: bb_bedpostx_gpu
#
# Description: Script to run bedpostx with the special needs for UK Biobank.
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

. $BB_BIN_DIR/bb_pipeline_tools/bb_set_header 

subjdir=`fsl_abspath $1`
subjdir=`echo ${subjdir} | sed 's/\/$/$/g'`
echo subjectdir is $subjdir

FSLSUBALREADYRUN=false
echo $FSLSUBALREADYRUN


if [ -d ${subjdir} ] ; then

    if [ ! -f ${subjdir}/pre_bedpostx_error.txt ] ; then
        #echo yes!!
        #opts="--nf=3 --fudge=1 --bi=3000 --nj=1250 --se=25 --model=2 --cnonlinear"
        #nvox=`cat ${subjdir}.bedpostX/nvox.txt`
	#echo yes yes
        #${FSLDIR}/bin/xfibres --data=${subjdir}.bedpostX/data_0 --mask=${subjdir}.bedpostX/nodif_brain_mask -b ${subjdir}.bedpostX/bvals -r ${subjdir}.bedpostX/bvecs --forcedir --logdir=${subjdir}.bedpostX/diff_parts/data_part_0000 $opts ${subjdir} 0 1 $nvox
        #cd ${subjdir}/bedpostx
        ${FSLDIR}/bin/bedpostx $subjdir/bedpostx --forcedir -V --nf=3 --bi=3000 --cnonlinear
	#cd ../../
	file=${subjdir}/bedpostx.bedpostX/merged_ph1samples.nii.gz
	while [ ! -f "$file" ]
            do
	    sleep 1
        done
	sleep 1m
    fi
else
    echo "It was not possible to run BEDPOSTX on the subject. Check bedpostx directory"
fi

. $BB_BIN_DIR/bb_pipeline_tools/bb_set_footer 

