#!/bin/sh
#
# Script name: bb_dice
#
# Description: Script to calculate the DICE index of 2 images
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

${FSLDIR}/bin/fslmaths $1 -add $2 grot_sum
${FSLDIR}/bin/fslmaths grot_sum -thr 2 -bin grot_intersect
${FSLDIR}/bin/fslmaths grot_sum -bin grot_union

volIntersect=`${FSLDIR}/bin/fslstats grot_intersect -V | awk '{print $1}'`
volMaths=`${FSLDIR}/bin/fslstats grot_union -V | awk '{print $1}'`

${FSLDIR}/bin/imrm grot_sum grot_intersect grot_union

echo `echo "(2 * $volIntersect) / $volMaths" | bc -l`

