#!/usr/bin/env bash
#
# Script name: bb_revert_pipeline
#
# Description: Script to revert the changes in the naming of the files
#  			   after the pipeline processing.
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
function copyFunc {
    if [[ "$S" == "*.nii.gz" ]] ; then
        nam1=`remove_ext $1`;
        nam2=`remove_ext $2`;
    
        if [ -f "${nam}.json" ] ; then
            cp "${nam1}.json" "${nam2}.json";
        fi
        cp -r "$1" "$2";
    else
        cp -r "$1" "$2";
    fi
}

set -e

processedDir=$1
destinDir=$2

if [ "$destinDir" = "" ]; then
    echo "Youd did not specify a destination directory" 
    exit
fi

if [ ! -d $processedDir ] ; then
    echo "The original processed subject does not exist" 
    exit
fi

if [ -d $destinDir ] ; then
    echo "There is already a destination subject directory" 
    exit
fi

mkdir $destinDir;

direcs=`for elem in \`cat $BB_BIN_DIR/bb_data/revert_table.txt | awk '{print $2}'\` ; do dirname $elem ; done | sort | uniq`

for direc in $direcs ; do
    mkdir -p $destinDir/$direc
done

while read -r line ; do

    orig=`echo $line | awk '{print $1}'`
    dest=`echo $line | awk '{print $2}'`

    if [ -e $processedDir/$orig ] ; then
        copyFunc $processedDir/$orig $destinDir/$dest
    else
        echo "File/Dir $orig does not exist for subject in $1"
    fi

done < $BB_BIN_DIR/bb_data/revert_table.txt


