#!/usr/bin/env bash
#
# Script name: bb_get_dwell_time
#
# Description: Script to read the dwell time for a certain image.
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

fileName=$1
fileName_noExt=`remove_ext $fileName`

if [ -f ${fileName_noExt}.json ] ; then
    $BB_BIN_DIR/bb_general_tools/bb_read_json_field.py -F ${fileName_noExt}.json -f EffectiveEchoSpacing -m 1000 -r 4

else
    descrip=`${FSLDIR}/bin/fslval $fileName descrip`
    descripParts=(`echo $descrip | tr ';' ' '`)

    for elem in ${descripParts[@]} ; do

        fieldName=`echo $elem | awk 'BEGIN { FS = "=" } ; {print $1}'`
        fieldValue=`echo $elem | awk 'BEGIN { FS = "=" } ; {print $2}'`

        if [ "$fieldName" == "dwell" ] ; then
            echo $fieldValue
        fi

    done
fi
