#!/usr/bin/env bash
#
# Script name: bb_set_footer
#
# Description: Script to generate logging text at the end of the 
#              execution of any script in the pipeline
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set +x

PARENT_COMMAND="$0"
END=$(date +%s)
DIFF=$(( $END - $START ))
echo "The command $PARENT_COMMAND took $DIFF seconds"
echo "Ending time: "`date`
