#!/usr/bin/env bash
#
# Script name: bb_tbss_general
#
# Description: General script to run the different phases of TBSS
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

. "$BB_BIN_DIR"/bb_pipeline_tools/bb_set_header 

direc="$PWD"/"$1"
TBSSDir="$direc"/dMRI/TBSS

mkdir "$TBSSDir"
cd "$TBSSDir"

ln ../dMRI/dti_FA.nii.gz dti_FA.nii.gz

"$BB_BIN_DIR"/bb_diffusion_pipeline/bb_tbss/bb_tbss_1_preproc dti_FA
"$BB_BIN_DIR"/bb_diffusion_pipeline/bb_tbss/bb_tbss_2_reg -T
"$BB_BIN_DIR"/bb_diffusion_pipeline/bb_tbss/bb_tbss_3_postreg -T
"$BB_BIN_DIR"/bb_diffusion_pipeline/bb_tbss/bb_tbss_4_prestats 2000
"$BB_BIN_DIR"/bb_diffusion_pipeline/bb_tbss/bb_tbss_non_FA

cd "$direc"

. "$BB_BIN_DIR"/bb_pipeline_tools/bb_set_footer 
