#!/usr/bin/env bash
#
# Script name: bb_tbss_1_preproc
#
# Description: Script to run the first phase of TBSS.
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
[ "$1" = "" ] && Usage

echo [`date`] [`hostname`] [`uname -a`] [`pwd`] [$0 $@] 

mkdir -p FA

for f in `$FSLDIR/bin/imglob $@` ; do

    echo processing $f

    # erode a little and zero end slices
    X=`${FSLDIR}/bin/fslval $f dim1`; X=`echo "$X 2 - p" | dc -`
    Y=`${FSLDIR}/bin/fslval $f dim2`; Y=`echo "$Y 2 - p" | dc -`
    Z=`${FSLDIR}/bin/fslval $f dim3`; Z=`echo "$Z 2 - p" | dc -`
    $FSLDIR/bin/fslmaths $f -min 1 -ero -roi 1 $X 1 $Y 1 $Z 0 1 FA/${f}

    # create mask (for use in FLIRT & FNIRT)
    $FSLDIR/bin/fslmaths FA/${f} -bin FA/${f}_mask

    $FSLDIR/bin/fslmaths FA/${f}_mask -dilD -dilD -sub 1 -abs -add FA/${f}_mask FA/${f}_mask -odt char
	
done

echo "Now running \"slicesdir\" to generate report of all input images"
cd FA
$FSLDIR/bin/slicesdir `$FSLDIR/bin/imglob *_FA.*` > grot 2>&1
cat grot | tail -n 2
/bin/rm grot

