#!/usr/bin/env bash
#
# Script name: bb_tbss_non_FA
#
# Description: Script to apply TBBS transformation to dMRI outputs other than FA
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
cd stats

dtifitDir=../../dMRI/

suffix="L1 L2 L3 MO MD"

for elem in $suffix ; do
    "$FSLDIR"/bin/applywarp --rel -i $dtifitDir/dti_$elem -o all_"$elem" -r "$FSLDIR"/data/standard/FMRIB58_FA_1mm -w ../FA/dti_FA_to_MNI_warp
    "$FSLDIR"/bin/fslmaths all_"$elem" -mas mean_FA_skeleton_mask all_"$elem"_skeletonised
    "$FSLDIR"/bin/fslstats -K "$FSLDIR"/data/atlases/JHU/JHU-ICBM-labels-1mm all_"$elem"_skeletonised.nii.gz -M >JHUrois_"$elem".txt
done

cd ..

