#!/bin/sh
#
# Script name: tvb_eddyQUAD
#
# Description: Script to run eddy_quad as part of eddyQC
#
## Author: Kelly Shen


. $BB_BIN_DIR/bb_pipeline_tools/bb_set_header 

baseDir=$PWD/$1

mkdir -p ${baseDir}/QC/eddyQUAD

${FSLDIR}/bin/eddy_quad ${baseDir}/dMRI/dMRI/data -idx ${baseDir}/dMRI/dMRI/eddy_index.txt -par ${baseDir}/dMRI/dMRI/acqparams.txt -m ${baseDir}/dMRI/dMRI/nodif_brain_mask.nii.gz -b ${baseDir}/dMRI/dMRI/bvals -o ${baseDir}/QC/eddyQUAD


. $BB_BIN_DIR/bb_pipeline_tools/bb_set_footer